# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Equipes
algerie = Team.create(name: 'Algérie')
cote_d_ivoire = Team.create(name: 'Côte d\'Ivoire')
nigeria = Team.create(name: 'Nigeria')
cameroun = Team.create(name: 'Cameroun')
ghana = Team.create(name: 'Ghana')
argentine = Team.create(name: 'Argentine')
chili = Team.create(name: 'Chili')
equateur = Team.create(name: 'Equateur')
bresil = Team.create(name: 'Brésil')
colombie = Team.create(name: 'Colombie')
uruguay = Team.create(name: 'Uruguay')
costa_rica = Team.create(name: 'Costa Rica')
mexique = Team.create(name: 'Mexique')
honduras = Team.create(name: 'Honduras')
usa = Team.create(name: 'USA')
australie = Team.create(name: 'Australie')
japon = Team.create(name: 'Japon')
iran = Team.create(name: 'Iran')
republique_de_coree = Team.create(name: 'République de Corée')
allemagne = Team.create(name: 'Allemagne')
belgique = Team.create(name: 'Belgique')
croatie = Team.create(name: 'Croatie')
france = Team.create(name: 'France')
italie = Team.create(name: 'Italie')
portugal = Team.create(name: 'Portugal')
suisse = Team.create(name: 'Suisse')
angleterre = Team.create(name: 'Angleterre')
bosnie = Team.create(name: 'Bosnie-Herzégovine')
espagne = Team.create(name: 'Espagne')
grece = Team.create(name: 'Grèce')
pays_bas = Team.create(name: 'Pays-Bas')
russie = Team.create(name: 'Russie')
groups_stage = Stage.create(name: 'Phase de groupes')
second_stage = Stage.create(name: 'Deuxième phase')

# Groupes
group_a = Group.create(name: 'Groupe A', stage_id: groups_stage.id)
group_b = Group.create(name: 'Groupe B', stage_id: groups_stage.id)
group_c = Group.create(name: 'Groupe C', stage_id: groups_stage.id)
group_d = Group.create(name: 'Groupe D', stage_id: groups_stage.id)
group_e = Group.create(name: 'Groupe E', stage_id: groups_stage.id)
group_f = Group.create(name: 'Groupe F', stage_id: groups_stage.id)
group_g = Group.create(name: 'Groupe G', stage_id: groups_stage.id)
group_h = Group.create(name: 'Groupe H', stage_id: groups_stage.id)
group_huitiemes = Group.create(name: 'Huitièmes de finale', stage_id: second_stage.id)
group_quart = Group.create(name: 'Quart de finale', stage_id: second_stage.id)
group_demi = Group.create(name: 'Demi-finales', stage_id: second_stage.id)
group_finale = Group.create(name: 'Finale', stage_id: second_stage.id)

# Matches
match_1  = Match.create(group_id: group_a.id, team_a_id: bresil.id, team_b_id: croatie.id, date: '20140612170000')
match_2  = Match.create(group_id: group_a.id, team_a_id: mexique.id, team_b_id: cameroun.id, date: '20140613130000')
match_3  = Match.create(group_id: group_b.id, team_a_id: espagne.id, team_b_id: pays_bas.id, date: '20140613160000')
match_4  = Match.create(group_id: group_b.id, team_a_id: chili.id, team_b_id: australie.id, date: '20140613180000')
match_5  = Match.create(group_id: group_c.id, team_a_id: colombie.id, team_b_id: grece.id, date: '20140614130000')
match_6  = Match.create(group_id: group_c.id, team_a_id: cote_d_ivoire.id, team_b_id: japon.id, date: '20140614220000')
match_7  = Match.create(group_id: group_d.id, team_a_id: uruguay.id, team_b_id: costa_rica.id, date: '20140614160000')
match_8  = Match.create(group_id: group_d.id, team_a_id: angleterre.id, team_b_id: italie.id, date: '20140614180000')
match_9  = Match.create(group_id: group_e.id, team_a_id: suisse.id, team_b_id: equateur.id, date: '20140615130000')
match_10 = Match.create(group_id: group_e.id, team_a_id: france.id, team_b_id: honduras.id, date: '20140615160000')
match_11 = Match.create(group_id: group_f.id, team_a_id: argentine.id, team_b_id: bosnie.id, date: '20140615190000')
match_12 = Match.create(group_id: group_f.id, team_a_id: iran.id, team_b_id: nigeria.id, date: '20140616160000')
match_13 = Match.create(group_id: group_g.id, team_a_id: allemagne.id, team_b_id: portugal.id, date: '20140616130000')
match_14 = Match.create(group_id: group_g.id, team_a_id: ghana.id, team_b_id: usa.id, date: '20140616190000')
match_15 = Match.create(group_id: group_h.id, team_a_id: belgique.id, team_b_id: algerie.id, date: '20140617130000')
match_16 = Match.create(group_id: group_h.id, team_a_id: russie.id, team_b_id: republique_de_coree.id, date: '20140617180000')
match_17 = Match.create(group_id: group_a.id, team_a_id: bresil.id, team_b_id: mexique.id, date: '20140617160000')
match_18 = Match.create(group_id: group_a.id, team_a_id: cameroun.id, team_b_id: croatie.id, date: '20140618180000')
match_19 = Match.create(group_id: group_b.id, team_a_id: espagne.id, team_b_id: chili.id, date: '20140618160000')
match_20 = Match.create(group_id: group_b.id, team_a_id: australie.id, team_b_id: pays_bas.id, date: '20140618130000')
match_21 = Match.create(group_id: group_c.id, team_a_id: colombie.id, team_b_id: cote_d_ivoire.id, date: '20140619130000')
match_22 = Match.create(group_id: group_c.id, team_a_id: japon.id, team_b_id: grece.id, date: '20140619190000')
match_23 = Match.create(group_id: group_d.id, team_a_id: uruguay.id, team_b_id: angleterre.id, date: '20140619160000')
match_24 = Match.create(group_id: group_d.id, team_a_id: italie.id, team_b_id: costa_rica.id, date: '20140620130000')
match_25 = Match.create(group_id: group_e.id, team_a_id: suisse.id, team_b_id: france.id, date: '20140620160000')
match_26 = Match.create(group_id: group_e.id, team_a_id: honduras.id, team_b_id: equateur.id, date: '20140620190000')
match_27 = Match.create(group_id: group_f.id, team_a_id: argentine.id, team_b_id: iran.id, date: '20140621130000')
match_28 = Match.create(group_id: group_f.id, team_a_id: nigeria.id, team_b_id: bosnie.id, date: '20140621180000')
match_29 = Match.create(group_id: group_g.id, team_a_id: allemagne.id, team_b_id: ghana.id, date: '20140621160000')
match_30 = Match.create(group_id: group_g.id, team_a_id: usa.id, team_b_id: portugal.id, date: '20140622180000')
match_31 = Match.create(group_id: group_h.id, team_a_id: belgique.id, team_b_id: russie.id, date: '20140622130000')
match_32 = Match.create(group_id: group_h.id, team_a_id: republique_de_coree.id, team_b_id: algerie.id, date: '20140622160000')
match_33 = Match.create(group_id: group_a.id, team_a_id: cameroun.id, team_b_id: bresil.id, date: '20140623170000')
match_34 = Match.create(group_id: group_a.id, team_a_id: croatie.id, team_b_id: mexique.id, date: '20140623170000')
match_35 = Match.create(group_id: group_b.id, team_a_id: australie.id, team_b_id: espagne.id, date: '20140623130000')
match_36 = Match.create(group_id: group_b.id, team_a_id: pays_bas.id, team_b_id: chili.id, date: '20140623130000')
match_37 = Match.create(group_id: group_c.id, team_a_id: japon.id, team_b_id: colombie.id, date: '20140624160000')
match_38 = Match.create(group_id: group_c.id, team_a_id: grece.id, team_b_id: cote_d_ivoire.id, date: '20140624170000')
match_39 = Match.create(group_id: group_d.id, team_a_id: italie.id, team_b_id: uruguay.id, date: '20140624160000')
match_40 = Match.create(group_id: group_d.id, team_a_id: costa_rica.id, team_b_id: angleterre.id, date: '20140624160000')
match_41 = Match.create(group_id: group_e.id, team_a_id: honduras.id, team_b_id: suisse.id, date: '20140625160000')
match_42 = Match.create(group_id: group_e.id, team_a_id: equateur.id, team_b_id: france.id, date: '20140625170000')
match_43 = Match.create(group_id: group_f.id, team_a_id: nigeria.id, team_b_id: argentine.id, date: '20140625130000')
match_44 = Match.create(group_id: group_f.id, team_a_id: bosnie.id, team_b_id: iran.id, date: '20140625130000')
match_45 = Match.create(group_id: group_g.id, team_a_id: usa.id, team_b_id: allemagne.id, date: '20140626130000')
match_46 = Match.create(group_id: group_g.id, team_a_id: portugal.id, team_b_id: ghana.id, date: '20140626130000')
match_47 = Match.create(group_id: group_h.id, team_a_id: republique_de_coree.id, team_b_id: belgique.id, date: '20140626170000')
match_48 = Match.create(group_id: group_h.id, team_a_id: algerie.id, team_b_id: russie.id, date: '20140626170000')

# classements
Standing.create(group_id: group_a.id, team_id: bresil.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_a.id, team_id: croatie.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_a.id, team_id: mexique.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_a.id, team_id: cameroun.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)

Standing.create(group_id: group_b.id, team_id: espagne.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_b.id, team_id: pays_bas.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_b.id, team_id: chili.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_b.id, team_id: australie.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)

Standing.create(group_id: group_c.id, team_id: colombie.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_c.id, team_id: grece.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_c.id, team_id: cote_d_ivoire.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_c.id, team_id: japon.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)

Standing.create(group_id: group_d.id, team_id: uruguay.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_d.id, team_id: costa_rica.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_d.id, team_id: angleterre.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_d.id, team_id: italie.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)

Standing.create(group_id: group_e.id, team_id: suisse.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_e.id, team_id: equateur.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_e.id, team_id: france.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_e.id, team_id: honduras.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)

Standing.create(group_id: group_f.id, team_id: argentine.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_f.id, team_id: bosnie.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_f.id, team_id: iran.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_f.id, team_id: nigeria.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)

Standing.create(group_id: group_g.id, team_id: allemagne.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_g.id, team_id: portugal.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_g.id, team_id: ghana.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_g.id, team_id: usa.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)

Standing.create(group_id: group_h.id, team_id: belgique.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_h.id, team_id: algerie.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_h.id, team_id: russie.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)
Standing.create(group_id: group_h.id, team_id: republique_de_coree.id, played: 0, won: 0, draw: 0, lost: 0, goals_for: 0, goals_against: 0, points: 0)

